### ISSUE TITLE
Create endpoint that utilizes query parameters

### ISSUE THREAD

**Issue by BrendenMarks** [cs481-ekh/f22-fires-wild#106]

**Comment by collins-benjaminw** [comment]
this could be useful: https://www.django-rest-framework.org/api-guide/filtering/#filtering-against-query-parameters

**Comment by BrendenMarks** [comment]
This story involved me spending time getting used to and understanding Django.  There were a few trials and tribulations including finding a way to deal with the requesting of fields dynamically in the serializer.  Without another package this does not seem very feasible.  With this PR, fields not requested by the user are returned as null and will be filtered out in the front end.  Another issue was figuring out how to build the query set using the QSPs before doing any data filtering for performance reasons.   Another concept that took some time was figuring out how to allow users to search using GTE, LTE, and BETWEEN.  Search using strictly equals was straight forward, but a couple helper functions were needed to implement these other search options.  With the required discovery, at least 8 hours was spent in total on this story.
