### ISSUE TITLE
Django api function security/locking

### ISSUE THREAD

**Issue by samwise-311** [cs481-ekh/f22-fires-wild#162]
As a user, I want to know that the data I am accessing is secure, so that I can have a reliable and comfortable experience.

## Definition of Done
- [ ] Have django api (not the Admin page) function locked to only accept requests from localhost:3000

## Tasks
- [ ] Task 1
- [ ] Task 2

**Comment by collins-benjaminw** [comment]
We should consider that cypress / devs needs to access the django endpoints in test environments, so we only want to lock down the endpoints in deployed environments

**Comment by collins-benjaminw** [comment]
This won't make sense actually, django api needs to be public
