### ISSUE TITLE
add search by ID to django admin page

### ISSUE THREAD

**Issue by collins-benjaminw** [cs481-ekh/f22-fires-wild#267]
As an admin, I want to search the admin page by FOD_ID, so that I can debug data problems

## Definition of Done
- [ ] In the admin page, a search box exists
- [ ] can find and view data based on entering FOD_ID (primary key)

## Tasks
- [ ] Task 1
- [ ] Task 2

**Comment by David5886** [comment]
This was taken care of by an outside contributor.
