### ISSUE TITLE
backend function to list variables

### ISSUE THREAD

**Issue by collins-benjaminw** [cs481-ekh/f22-fires-wild#37]
we need a backend function that returns a list of table column names (more likely model attribute names) for the variable selection dropdown

- [x] Create ListSerializer
- [x] Create function to list primary data specified by sponsor on the index 
- [x] Display data in console on index React page

**Comment by jeremystocking** [comment]
Variable lists are serialized at alocalhost:8000/api/variable_list
Data has been fetched on localhost:3000/data
