### ISSUE TITLE
dropdown on sidebar with unique values for variables

### ISSUE THREAD

**Issue by collins-benjaminw** [cs481-ekh/f22-fires-wild#40]
As a user, I need to be able to select filters for the data

depends on #39, #38, #37 

Acceptance Criteria
- [x] #141
- [ ] Sidebar with dropdowns for each variable from the request on #37
- [x] #143
- [ ] When user selects a state, add a county dropdown filled with values requested for unique counties where state = the state chosen

**Comment by samwise-311** [comment]
Created story in Sprint 3 for 2nd task and 4th task  --> #164
